group: macos tests
sort_key: "~macos"
steps:
  # block on premerge
  - block: "run macos tests"
    if: build.env("BUILDKITE_PIPELINE_ID") == "0189942e-0876-4b8f-80a4-617f988ec59b"

  - label: ":ray: core: :mac: small & client tests"
    if: build.env("BUILDKITE_PIPELINE_ID") != "0189e759-8c96-4302-b6b5-b4274406bf89"
    job_env: MACOS
    instance_type: macos
    commands:
      - ./ci/ray_ci/macos/macos_ci.sh run_small_test
